spring.application.name=api-gateway
server.port=8080

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

# Gateway Routes
spring.cloud.gateway.mvc.routes[0].id=product
spring.cloud.gateway.mvc.routes[0].uri=lb://product
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/products/**

spring.cloud.gateway.mvc.routes[1].id=order
spring.cloud.gateway.mvc.routes[1].uri=lb://order
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/orders/**

spring.cloud.gateway.mvc.routes[2].id=inventory
spring.cloud.gateway.mvc.routes[2].uri=lb://inventory
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/api/inventory/**
